import { metadata } from '../layout';

describe('Layout metadata', () => {
  it('should have the correct title', () => {
    expect(metadata.title).toBe("MHAHRR Natural's | Healing Solution");
  });

  it('should have the correct description', () => {
    expect(metadata.description).toBe('Generated by create next app');
  });

  it('should have the correct icon', () => {
    expect(metadata.icon).toBe('/images/logo_without_text_bgremove.png');
  });
});
